name: Build EXE and Release with Auto Tagging

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: Check if FbManager.py changed
        id: changed
        shell: bash
        run: |
          git fetch origin main
          if git diff --name-only origin/main | grep -q 'FbManager.py'; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5 firebase-admin

      - name: Firebase Key 복원
        shell: pwsh
        run: |
          [System.IO.File]::WriteAllBytes("skyelectricFbKey.json", [Convert]::FromBase64String("${{ secrets.FB_KEY_BASE64 }}"))

      - name: spec삭제
        shell: pwsh
        run: |
          Remove-Item -Force FbManager.spec -ErrorAction SilentlyContinue
          Remove-Item -Force Updater.spec -ErrorAction SilentlyContinue

      - name: Updater 빌드
        run: pyinstaller --noconfirm --onefile --windowed --distpath FbPgExe Updater.py

      - name: EXE 빌드
        if: steps.changed.outputs.changed == 'true'
        shell: pwsh
        run: |
          pyinstaller --noconfirm --onefile --windowed --add-data "skyelectricFbKey.json;." --distpath FbPgExe --workpath FbPgExe/build FbManager.py

      #- name: Firebase Key 삭제
      #  shell: pwsh
      #  run: Remove-Item -Force skyelectricFbKey.json
    
      - name: 커밋 메시지에서 태그 추출
        id: commit_tag
        shell: bash
        run: |
          TAG=$(git log -1 --pretty=%B | grep -oP '\[release:v\K[0-9.]+')
          if [ -z "$TAG" ]; then
            echo "custom_tag=" >> $GITHUB_OUTPUT
          else
            echo "custom_tag=v$TAG" >> $GITHUB_OUTPUT
          fi

      - name: 태그 만들기
        uses: mathieudutour/github-tag-action@v6.1
        id: tagger
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.commit_tag.outputs.custom_tag }}

          
      - name: 버전 쓰기
        run: |
          echo "${{steps.tagger.outputs.new_tag}}" >> FbPgExe/version.txt

      - name: FbPgExe압축
        run: Compress-Archive -Path FbPgExe\* -DestinationPath FbPgExe.zip
      

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.new_tag }}
          name: Release ${{ steps.tagger.outputs.new_tag }}
          files: FbPgExe.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
