name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5 firebase-admin

      - name: Firebase 키 복원 (PowerShell 사용)
        shell: pwsh
        run: |
          [System.IO.File]::WriteAllBytes("skyelectricFbKey.json", [Convert]::FromBase64String("${{ secrets.FB_KEY_BASE64 }}"))

      - name: 경로 확인
        run: dir

      - name: 기존 spec 파일 삭제
        shell: pwsh
        run: Remove-Item -Force FbManager.spec -ErrorAction SilentlyContinue

      - name: EXE 빌드
        shell: pwsh
        run: |
          pyinstaller --noconfirm --onefile --windowed --add-data "skyelectricFbKey.json;." --distpath FbPgExe --workpath FbPgExe/build FbManager.py

      - name: 키 파일 삭제
        shell: pwsh
        run: Remove-Item skyelectricFbKey.json

      - name: FbPgExe 폴더 압축
        run: Compress-Archive -Path FbPgExe\* -DestinationPath FbPgExe.zip

      - name: Release에 zip 파일 업로드
        uses: softprops/action-gh-release@v1
        with:
          files: FbPgExe.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
