name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5 firebase-admin

      - name: EXE 빌드
        run: |
          pyinstaller --noconfirm --onefile --windowed --add-data "skyelectricFbKey.json;." FbManager.py

      - name: Release에 실행파일 업로드
        uses: softprops/action-gh-release@v1
        with:
          files: dist/FbManager.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Firebase 키 복원
        run: |
          echo ${{ secrets.FB_KEY_BASE64 }} | base64 -d > skyelectricFbKey.json

