name: Build EXE and Release with Auto Tagging

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5 firebase-admin

      - name: 키 복원 전 폴더 생성
        shell: pwsh
        run: New-Item -ItemType Directory -Force -Path keys

      - name: Firebase Key 복원
        shell: pwsh
        run: |
          [System.IO.File]::WriteAllBytes("keys/skyelectricFbKey.json", [Convert]::FromBase64String("${{ secrets.FB_KEY_BASE64 }}"))

      - name: spec삭제
        shell: pwsh
        run: Remove-Item -Force FbManager.spec -ErrorAction SilentlyContinue

      - name: EXE 빌드
        shell: pwsh
        run: |
          pyinstaller --noconfirm --onefile --windowed --add-data "skyelectricFbKey.json;keys" --distpath FbPgExe --workpath FbPgExe/build FbManager.py

      - name: Firebase Key 삭제
        shell: pwsh
        run: Remove-Item -Force keys/skyelectricFbKey.json

      - name: FbPgExe압축
        run: Compress-Archive -Path FbPgExe\* -DestinationPath FbPgExe.zip

      - name: 자동태그
        uses: mathieudutour/github-tag-action@v6.1
        id: tagger
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.new_tag }}
          name: Release ${{ steps.tagger.outputs.new_tag }}
          files: FbPgExe.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
